#if UNITY_EDITOR
using System;
using UnityEngine;

namespace DeltaField.Shaders.MeshHologram.Editor
{
    public enum SHADER_PROPERTY
    {
        _RENDERING_MODE,
        _CULL,
        _Z_WRITE,

        _CUSTOM_RENDER_QUEUE_T,
        _CUSTOM_RENDER_QUEUE_C,

        _FORCED_Z_SCALE_ZERO,
        _BILLBOARD_MODE,
        _DISTANCE_INFLUENCE,
        _STEREO_MERGE_MODE,
        _USE_FWIDTH,

        _ACTIVATE_DIRECTIONAL_LIGHT_INFLUENCE,
        _DIRECTIONAL_LIGHT_INFLUENCE,

        _ACTIVATE_AMBIENT_INFLUENCE,
        _AMBIENT_INFLUENCE,

        _ACTIVATE_LIGHTVOLUMES_INFLUENCE,
        _LIGHTVOLUMES_INFLUENCE,

        _PREVIEW_MODE,
        _ANTI_ALIASING,

        _MAIN_TEX,

        _Z_CLIP,
        _Z_TEST,
        _COLOR_MASK,
        _OFFSET_FACTOR,
        _OFFSET_UNITS,
        _ALPHA_TO_MASK,

        _BLEND_OP,
        _SRC_BLEND,
        _DST_BLEND,
        _BLEND_OP_ALPHA,
        _SRC_BLEND_ALPHA,
        _DST_BLEND_ALPHA,

        _STENCIL_REF,
        _STENCIL_READ_MASK,
        _STENCIL_WRITE_MASK,
        _STENCIL_COMP,
        _STENCIL_PASS,
        _STENCIL_FAIL,
        _STENCIL_Z_FAIL,

        _USE_AUDIOLINK,
        _AUDIOLINK_VU_BAND,
        _AUDIOLINK_VU_SMOOTH,
        _AUDIOLINK_VU_PANNING,
        _AUDIOLINK_VU_GAIN_MUL,
        _AUDIOLINK_VU_GAIN_ADD,
        _AUDIOLINK_CHRONO_TENSITY_SCALE,
        _AUDIOLINK_CHRONO_TENSITY_TYPE,
        _AUDIOLINK_CHRONO_TENSITY_BAND,
        _AUDIOLINK_THEME_COLOR_BAND,


        _TRIANGLE_COMP,
        _FILL,
        _LINE_WIDTH,
        _LINE_GRADIENT_BIAS,
        _MANUAL_LINE_SCALING,
        _LINE_SCALE,
        _LINE_FADE_MODE,
        _FRAGMENT_VALUE,
        _FRAGMENT_INVERSE,
        _PARTITION_TYPE,


        _COLOR0,
        _COLOR1,
        _EMISSION,
        _COLOR_SOURCE,
        _COLOR_GRADIENT_TEX,
        _COLOR_VALUE,
        _COLORING_PARTITION_TYPE,


        _GEOMETRY_VALUE,

        _GEOMETRY_SCALE,
        _GEOMETRY_SCALE_RANGE,

        _GEOMETRY_EXTRUDE,
        _GEOMETRY_EXTRUDE_RANGE,

        _GEOMETRY_ROTATION,
        _GEOMETRY_ROTATION_REVERSE,
        _GEOMETRY_ROTATION_NOISE_REPEAT,

        _GEOMETRY_PARTITION_BIAS,
        _PIXELIZATION_SPACE,
        _PIXELIZATION,


        _ACTIVATE_ORBIT,

        _ORBIT_VALUE,
        _ORBIT_SEED,
        _ORBIT_PRIMITIVE_THRESHOLD,
        _ORBIT_OFFSET,
        _ORBIT_SCALE,

        _ORBIT_ROTATION_VALUE,
        _ORBIT_ROTATION_SEED,
        _ORBIT_ROTATION,
        _ORBIT_ROTATION_TIME_MULTIPLIER,

        _ORBIT_ROTATION_VARIANCE,

        _ORBIT_WAVE_FREQUENCY,
        _ORBIT_WAVE_STRENGTH,
        _ORBIT_WAVE_PHASE,
        _ORBIT_WAVE_TIME_MULTIPLIER,

        _ORBIT_ROTATION_REF_AUDIOLINK,
        _ORBIT_ROTATION_AUDIOLINK_STRENGTH,

        _ORBIT_WAVE_REF_AUDIOLINK,
        _ORBIT_WAVE_AUDIOLINK_STRENGTH,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_MIRROR,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_TYPE,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_RANGE,


        _FRAGMENT_SOURCE,
        _COLORING_SOURCE,
        _GEOMETRY_SOURCE,
        _ORBIT_SOURCE,
        _ORBIT_ROTATION_SOURCE,


        _AUDIOLINK_MASK_CONTROL_TEX,
        _AUDIOLINK_MASK_CONTROL,
        _FRAGMENT_MASK_CONTROL_TEX,
        _FRAGMENT_MASK_CONTROL,
        _COLORING_MASK_CONTROL_TEX,
        _COLORING_MASK_CONTROL,
        _GEOMETRY_MASK_CONTROL_TEX,
        _GEOMETRY_MASK_CONTROL,
        _ORBIT_MASK_CONTROL_TEX,
        _ORBIT_MASK_CONTROL,
        _NOISE1ST_OFFSET_CONTROL_TEX,
        _NOISE1ST_OFFSET_CONTROL,
        _NOISE2ND_OFFSET_CONTROL_TEX,
        _NOISE2ND_OFFSET_CONTROL,
        _NOISE3RD_OFFSET_CONTROL_TEX,
        _NOISE3RD_OFFSET_CONTROL,


        _FRAGMENT_AUDIOLINK_NOISE_SPECTRUM,
        _COLORING_AUDIOLINK_NOISE_SPECTRUM,
        _GEOMETRY_AUDIOLINK_NOISE_SPECTRUM,

        _FRAGMENT_AUDIOLINK_STRENGTH,
        _FRAGMENT_AUDIOLINK_SPECTRUM_MIRROR,
        _FRAGMENT_AUDIOLINK_SPECTRUM_TYPE,
        _FRAGMENT_AUDIOLINK_SPECTRUM_RANGE,

        _COLORING_AUDIOLINK_STRENGTH,
        _COLORING_AUDIOLINK_SPECTRUM_MIRROR,
        _COLORING_AUDIOLINK_SPECTRUM_TYPE,
        _COLORING_AUDIOLINK_SPECTRUM_RANGE,

        _GEOMETRY_AUDIOLINK_STRENGTH,
        _GEOMETRY_AUDIOLINK_SPECTRUM_MIRROR,
        _GEOMETRY_AUDIOLINK_SPECTRUM_TYPE,
        _GEOMETRY_AUDIOLINK_SPECTRUM_RANGE,


        _NOISE1ST_SPACE,
        _NOISE2ND_SPACE,
        _NOISE3RD_SPACE,

        _NOISE1ST_OFFSET0,
        _NOISE1ST_SCALE0,
        _NOISE1ST_OFFSET1,
        _NOISE1ST_SCALE1,
        _NOISE1ST_OFFSET_BEFORE_SCALE,
        _NOISE1ST_SEED,
        _NOISE1ST_VALUE_CURVE,
        _NOISE1ST_CURVE_TYPE,
        _NOISE1ST_THRESHOLD_MUL,
        _NOISE1ST_THRESHOLD_ADD,
        _NOISE1ST_TIME_MULTI,
        _NOISE1ST_TIME_PHASE,
        _NOISE1ST_PHASE_SCALE,
        _NOISE1ST_PHASE_REF_AUDIOLINK,

        _NOISE2ND_OFFSET0,
        _NOISE2ND_SCALE0,
        _NOISE2ND_OFFSET1,
        _NOISE2ND_SCALE1,
        _NOISE2ND_OFFSET_BEFORE_SCALE,
        _NOISE2ND_SEED,
        _NOISE2ND_VALUE_CURVE,
        _NOISE2ND_CURVE_TYPE,
        _NOISE2ND_THRESHOLD_MUL,
        _NOISE2ND_THRESHOLD_ADD,
        _NOISE2ND_TIME_MULTI,
        _NOISE2ND_TIME_PHASE,
        _NOISE2ND_PHASE_SCALE,
        _NOISE2ND_PHASE_REF_AUDIOLINK,

        _NOISE3RD_OFFSET0,
        _NOISE3RD_SCALE0,
        _NOISE3RD_OFFSET1,
        _NOISE3RD_SCALE1,
        _NOISE3RD_OFFSET_BEFORE_SCALE,
        _NOISE3RD_SEED,
        _NOISE3RD_VALUE_CURVE,
        _NOISE3RD_CURVE_TYPE,
        _NOISE3RD_THRESHOLD_MUL,
        _NOISE3RD_THRESHOLD_ADD,
        _NOISE3RD_TIME_MULTI,
        _NOISE3RD_TIME_PHASE,
        _NOISE3RD_PHASE_SCALE,
        _NOISE3RD_PHASE_REF_AUDIOLINK,
    }

    public enum CUSTOM_GUI
    {
        PLAIN,
        TITLE0,
        TITLE1,
        HEADER0,
        HEADER1,
    }

    public enum TITLE_SKINS
    {
        NORMAL,
        RAINBOW,
        SPREAD,
        DAY_AND_NIGHT,
    }

    public enum LANG
    {
        [Obsolete]
        PROPERTY = 0,
        ENGLISH = 1,
        JAPANESE = 2,
    }

    public enum FOLDOUT
    {
        RENDERING,
        RENDERING_OTHER,
        STENCIL,
        AUDIOLINK,
        FRAGMENT,
        COLOR,
        GEOMETRY,
        ORBIT,
        NOISE1ST,
        NOISE2ND,
        NOISE3RD,
        OTHERS
    }
}

#endif