#if UNITY_EDITOR
using System;
using UnityEngine;

namespace DeltaField.Shaders.MeshHologram.Editor
{
    public enum SHADER_PROPERTY
    {
        _EMPTY = -1,
        _RENDERING_MODE,
        _CULL,
        _Z_WRITE,

        _CUSTOM_RENDER_QUEUE_T,
        _CUSTOM_RENDER_QUEUE_C,

        _FORCED_Z_SCALE_ZERO,
        _BILLBOARD_ENABLE,
        _DISTANCE_INFLUENCE,
        _STEREO_MERGE_MODE,
        _FWIDTH_ENABLE,

        _DIRECTIONAL_LIGHT_INFLUENCE_ENABLE,
        _DIRECTIONAL_LIGHT_INFLUENCE,

        _AMBIENT_INFLUENCE_ENABLE,
        _AMBIENT_INFLUENCE,

        _LIGHTVOLUMES_INFLUENCE_ENABLE,
        _LIGHTVOLUMES_INFLUENCE,

        _PREVIEW_ENABLE,
        _ANTI_ALIASING_ENABLE,

        _MAIN_TEX,

        _Z_CLIP,
        _Z_TEST,
        _COLOR_MASK,
        _OFFSET_FACTOR,
        _OFFSET_UNITS,
        _ALPHA_TO_MASK,

        _BLEND_OP,
        _SRC_BLEND,
        _DST_BLEND,
        _BLEND_OP_ALPHA,
        _SRC_BLEND_ALPHA,
        _DST_BLEND_ALPHA,

        _STENCIL_REF,
        _STENCIL_READ_MASK,
        _STENCIL_WRITE_MASK,
        _STENCIL_COMP,
        _STENCIL_PASS,
        _STENCIL_FAIL,
        _STENCIL_Z_FAIL,

        _AUDIOLINK_ENABLE,
        _AUDIOLINK_THEME_COLOR_BAND,

        _FRAGMENT_TRIANGLE_COMPRESSION,
        _FRAGMENT_FILL,
        _FRAGMENT_LINE_WIDTH,
        _FRAGMENT_LINE_GRADIENT_BIAS,
        _FRAGMENT_MANUAL_LINE_SCALING,
        _FRAGMENT_LINE_SCALE,
        _FRAGMENT_LINE_ANIMATION_MODE,
        _FRAGMENT_INVERSE,
        _FRAGMENT_PARTITION_MODE,


        _COLOR0,
        _COLOR1,
        _EMISSION,
        _COLOR_SOURCE,
        _COLOR_GRADIENT_TEX,
        _COLORING_PARTITION_MODE,


        _GEOMETRY_SCALE_ENABLE,
        _GEOMETRY_SCALE_BOUNDS,

        _GEOMETRY_PUSHPULL_ENABLE,
        _GEOMETRY_PUSHPULL_BOUNDS,
        _GEOMETRY_PUSHPULL_PARTITION_BIAS,

        _GEOMETRY_ROTATION_ENABLE,
        _GEOMETRY_ROTATION_STRENGTH,
        _GEOMETRY_ROTATION_INVERT,
        _GEOMETRY_ROTATION_NOISE_REPEAT,

        _GEOMETRY_PIXELIZATION_SPACE,
        _GEOMETRY_PIXELIZATION,


        _ORBIT_ENABLE,

        _ORBIT_SEED,
        _ORBIT_PRIMITIVE_RATIO,
        _ORBIT_OFFSET,
        _ORBIT_SCALE,

        _ORBIT_ROTATION_SEED,
        _ORBIT_ROTATION_ANGLE,
        _ORBIT_ROTATION_SPEED,

        _ORBIT_ROTATION_SPREAD,

        _ORBIT_WAVE_STRENGTH,
        _ORBIT_WAVE_FREQUENCY,
        _ORBIT_WAVE_PHASE,
        _ORBIT_WAVE_SPEED,



        _FRAGMENT_SOURCE,
        _FRAGMENT_FIXED_VALUE,
        _FRAGMENT_AUDIOLINK_SOURCE,
        _FRAGMENT_AUDIOLINK_VU_BAND,
        _FRAGMENT_AUDIOLINK_VU_SMOOTHING,
        _FRAGMENT_AUDIOLINK_VU_PANNING,
        _FRAGMENT_AUDIOLINK_VU_STRENGTH,
        _FRAGMENT_AUDIOLINK_CHRONO_TENSITY_MODE,
        _FRAGMENT_AUDIOLINK_CHRONO_TENSITY_BAND,
        _FRAGMENT_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
        _FRAGMENT_AUDIOLINK_SPECTRUM_STRENGTH,
        _FRAGMENT_AUDIOLINK_SPECTRUM_MIRROR,
        _FRAGMENT_PHASE_SCALE,
        _FRAGMENT_LOOP_MODE,
        _FRAGMENT_EASE_MODE,
        _FRAGMENT_EASE_CURVE,
        _FRAGMENT_MID_MUL,
        _FRAGMENT_MID_ADD,


        _COLORING_SOURCE,
        _COLORING_FIXED_VALUE,
        _COLORING_AUDIOLINK_SOURCE,
        _COLORING_AUDIOLINK_VU_BAND,
        _COLORING_AUDIOLINK_VU_SMOOTHING,
        _COLORING_AUDIOLINK_VU_PANNING,
        _COLORING_AUDIOLINK_VU_STRENGTH,
        _COLORING_AUDIOLINK_CHRONO_TENSITY_MODE,
        _COLORING_AUDIOLINK_CHRONO_TENSITY_BAND,
        _COLORING_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
        _COLORING_AUDIOLINK_SPECTRUM_STRENGTH,
        _COLORING_AUDIOLINK_SPECTRUM_MIRROR,
        _COLORING_PHASE_SCALE,
        _COLORING_LOOP_MODE,
        _COLORING_EASE_MODE,
        _COLORING_EASE_CURVE,
        _COLORING_MID_MUL,
        _COLORING_MID_ADD,


        _GEOMETRY_SOURCE,
        _GEOMETRY_AUDIOLINK_SOURCE,
        _GEOMETRY_AUDIOLINK_VU_BAND,
        _GEOMETRY_AUDIOLINK_VU_SMOOTHING,
        _GEOMETRY_AUDIOLINK_VU_PANNING,
        _GEOMETRY_AUDIOLINK_VU_STRENGTH,
        _GEOMETRY_AUDIOLINK_CHRONO_TENSITY_MODE,
        _GEOMETRY_AUDIOLINK_CHRONO_TENSITY_BAND,
        _GEOMETRY_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
        _GEOMETRY_AUDIOLINK_SPECTRUM_STRENGTH,
        _GEOMETRY_AUDIOLINK_SPECTRUM_MIRROR,
        _GEOMETRY_FIXED_VALUE,
        _GEOMETRY_PHASE_SCALE,
        _GEOMETRY_LOOP_MODE,
        _GEOMETRY_EASE_MODE,
        _GEOMETRY_EASE_CURVE,
        _GEOMETRY_MID_MUL,
        _GEOMETRY_MID_ADD,


        _ORBIT_SOURCE,
        _ORBIT_AUDIOLINK_SOURCE,
        _ORBIT_AUDIOLINK_VU_BAND,
        _ORBIT_AUDIOLINK_VU_SMOOTHING,
        _ORBIT_AUDIOLINK_VU_PANNING,
        _ORBIT_AUDIOLINK_VU_STRENGTH,
        _ORBIT_AUDIOLINK_CHRONO_TENSITY_MODE,
        _ORBIT_AUDIOLINK_CHRONO_TENSITY_BAND,
        _ORBIT_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
        _ORBIT_AUDIOLINK_SPECTRUM_STRENGTH,
        _ORBIT_AUDIOLINK_SPECTRUM_MIRROR,
        _ORBIT_FIXED_VALUE,
        _ORBIT_PHASE_SCALE,
        _ORBIT_LOOP_MODE,
        _ORBIT_EASE_MODE,
        _ORBIT_EASE_CURVE,
        _ORBIT_MID_MUL,
        _ORBIT_MID_ADD,


        _ORBIT_ROTATION_SOURCE,
        _ORBIT_ROTATION_FIXED_VALUE,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_SOURCE,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_BAND,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_SMOOTHING,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_PANNING,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_STRENGTH,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_CHRONO_TENSITY_MODE,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_CHRONO_TENSITY_BAND,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_CHRONO_TENSITY_STRENGTH,

        _ORBIT_WAVE_AUDIOLINK_SOURCE,
        _ORBIT_WAVE_AUDIOLINK_VU_BAND,
        _ORBIT_WAVE_AUDIOLINK_VU_SMOOTHING,
        _ORBIT_WAVE_AUDIOLINK_VU_PANNING,
        _ORBIT_WAVE_AUDIOLINK_VU_STRENGTH,
        _ORBIT_WAVE_AUDIOLINK_CHRONO_TENSITY_MODE,
        _ORBIT_WAVE_AUDIOLINK_CHRONO_TENSITY_BAND,
        _ORBIT_WAVE_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_STRENGTH,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_MIRROR,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_MODE,
        _ORBIT_WAVE_AUDIOLINK_SPECTRUM_BOUNDS,



        _FRAGMENT_MASK_CONTROL_TEX,
        _FRAGMENT_MASK_CONTROL,
        _COLORING_MASK_CONTROL_TEX,
        _COLORING_MASK_CONTROL,
        _GEOMETRY_MASK_CONTROL_TEX,
        _GEOMETRY_MASK_CONTROL,
        _ORBIT_MASK_CONTROL_TEX,
        _ORBIT_MASK_CONTROL,
        _ORBIT_ROTATION_MASK_CONTROL_TEX,
        _ORBIT_ROTATION_MASK_CONTROL,
        _ORBIT_ROTATION_OFFSET_MASK_CONTROL_TEX,
        _ORBIT_ROTATION_OFFSET_MASK_CONTROL,

        _FRAGMENT_OFFSET_CONTROL_TEX,
        _FRAGMENT_OFFSET_CONTROL,
        _COLORING_OFFSET_CONTROL_TEX,
        _COLORING_OFFSET_CONTROL,
        _GEOMETRY_OFFSET_CONTROL_TEX,
        _GEOMETRY_OFFSET_CONTROL,
        _ORBIT_OFFSET_CONTROL_TEX,
        _ORBIT_OFFSET_CONTROL,
        _ORBIT_ROTATION_OFFSET_CONTROL_TEX,
        _ORBIT_ROTATION_OFFSET_CONTROL,

        _FRAGMENT_AUDIOLINK_MASK_CONTROL_TEX,
        _FRAGMENT_AUDIOLINK_MASK_CONTROL,
        _COLORING_AUDIOLINK_MASK_CONTROL_TEX,
        _COLORING_AUDIOLINK_MASK_CONTROL,
        _GEOMETRY_AUDIOLINK_MASK_CONTROL_TEX,
        _GEOMETRY_AUDIOLINK_MASK_CONTROL,
        _ORBIT_AUDIOLINK_MASK_CONTROL_TEX,
        _ORBIT_AUDIOLINK_MASK_CONTROL,
        //
        //
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_MASK_CONTROL_TEX,
        _ORBIT_ROTATION_OFFSET_AUDIOLINK_MASK_CONTROL,

        _FRAGMENT_NOISE_SPACE,
        _COLORING_NOISE_SPACE,
        _GEOMETRY_NOISE_SPACE,
        _ORBIT_NOISE_SPACE,
        _ORBIT_ROTATION_NOISE_SPACE,

        _FRAGMENT_NOISE_OFFSET0,
        _FRAGMENT_NOISE_SCALE0,
        _FRAGMENT_NOISE_OFFSET1,
        _FRAGMENT_NOISE_SCALE1,
        _FRAGMENT_NOISE_OFFSET_BEFORE_SCALE,
        _FRAGMENT_NOISE_SEED,
        _FRAGMENT_NOISE_TIME_SPEED,
        _FRAGMENT_NOISE_TIME_PHASE,
        _FRAGMENT_NOISE_VALUE_SCALE,

        _COLORING_NOISE_OFFSET0,
        _COLORING_NOISE_SCALE0,
        _COLORING_NOISE_OFFSET1,
        _COLORING_NOISE_SCALE1,
        _COLORING_NOISE_OFFSET_BEFORE_SCALE,
        _COLORING_NOISE_SEED,
        _COLORING_NOISE_TIME_SPEED,
        _COLORING_NOISE_TIME_PHASE,
        _COLORING_NOISE_VALUE_SCALE,

        _GEOMETRY_NOISE_OFFSET0,
        _GEOMETRY_NOISE_SCALE0,
        _GEOMETRY_NOISE_OFFSET1,
        _GEOMETRY_NOISE_SCALE1,
        _GEOMETRY_NOISE_OFFSET_BEFORE_SCALE,
        _GEOMETRY_NOISE_SEED,
        _GEOMETRY_NOISE_TIME_SPEED,
        _GEOMETRY_NOISE_TIME_PHASE,
        _GEOMETRY_NOISE_VALUE_SCALE,

        _ORBIT_NOISE_OFFSET0,
        _ORBIT_NOISE_SCALE0,
        _ORBIT_NOISE_OFFSET1,
        _ORBIT_NOISE_SCALE1,
        _ORBIT_NOISE_OFFSET_BEFORE_SCALE,
        _ORBIT_NOISE_SEED,
        _ORBIT_NOISE_TIME_SPEED,
        _ORBIT_NOISE_TIME_PHASE,
        _ORBIT_NOISE_VALUE_SCALE,

        _ORBIT_ROTATION_NOISE_OFFSET0,
        _ORBIT_ROTATION_NOISE_SCALE0,
        _ORBIT_ROTATION_NOISE_OFFSET1,
        _ORBIT_ROTATION_NOISE_SCALE1,
        _ORBIT_ROTATION_NOISE_OFFSET_BEFORE_SCALE,
        _ORBIT_ROTATION_NOISE_SEED,
        _ORBIT_ROTATION_NOISE_TIME_SPEED,
        _ORBIT_ROTATION_NOISE_TIME_PHASE,
        _ORBIT_ROTATION_NOISE_VALUE_SCALE
    }

    public enum CUSTOM_GUI
    {
        PLAIN,
        TITLE0,
        TITLE1,
        HEADER0,
        HEADER1,
    }

    public enum TITLE_SKINS
    {
        NORMAL,
        RAINBOW,
        SPREAD,
        DAY_AND_NIGHT,
    }

    public enum LANG
    {
        [Obsolete]
        PROPERTY = 0,
        ENGLISH = 1,
        JAPANESE = 2,
    }

    public enum FOLDOUT
    {
        RENDERING,
        RENDERING_OTHER,
        STENCIL,
        AUDIOLINK,
        FRAGMENT,
        COLOR,
        GEOMETRY,
        ORBIT,
        MASK_OFFSET,
        SOURCE,
        AUDIOLINK_SOURCE,
        MODIFIER,
        OTHERS
    }
}

#endif