#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.Linq;

namespace DeltaField.Shaders.MeshHologram.Editor
{
    public static partial class PropertyBlockManager
    {
        public static readonly Dictionary<PROPERTY_BLOCK, PropertyBlock> PropertyBlockNames = new Dictionary<PROPERTY_BLOCK, PropertyBlock>()
        {
            {PROPERTY_BLOCK.RENDERING,new PropertyBlock("Rendering",
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._RENDERING_MODE,
                    MESHHOLOGRAM_PROP_ENUM._CULL,
                    MESHHOLOGRAM_PROP_ENUM._Z_WRITE,
                    MESHHOLOGRAM_PROP_ENUM._CUSTOM_RENDER_QUEUE_T,
                    MESHHOLOGRAM_PROP_ENUM._CUSTOM_RENDER_QUEUE_C,
                    MESHHOLOGRAM_PROP_ENUM._FORCED_Z_SCALE_ZERO,
                    MESHHOLOGRAM_PROP_ENUM._BILLBOARD_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._DISTANCE_INFLUENCE,
                    MESHHOLOGRAM_PROP_ENUM._STEREO_MERGE_MODE,
                    MESHHOLOGRAM_PROP_ENUM._FWIDTH_ENABLE,

                    MESHHOLOGRAM_PROP_ENUM._DIRECTIONAL_LIGHT_INFLUENCE_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._DIRECTIONAL_LIGHT_INFLUENCE,
                    MESHHOLOGRAM_PROP_ENUM._AMBIENT_INFLUENCE_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._AMBIENT_INFLUENCE,
                    MESHHOLOGRAM_PROP_ENUM._LIGHTVOLUMES_INFLUENCE_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._LIGHTVOLUMES_INFLUENCE,
                    MESHHOLOGRAM_PROP_ENUM._PREVIEW_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._ANTI_ALIASING_ENABLE,

                    MESHHOLOGRAM_PROP_ENUM._MAIN_TEX,

                    MESHHOLOGRAM_PROP_ENUM._Z_CLIP,
                    MESHHOLOGRAM_PROP_ENUM._Z_TEST,
                    MESHHOLOGRAM_PROP_ENUM._COLOR_MASK,
                    MESHHOLOGRAM_PROP_ENUM._OFFSET_FACTOR,
                    MESHHOLOGRAM_PROP_ENUM._OFFSET_UNITS,
                    MESHHOLOGRAM_PROP_ENUM._ALPHA_TO_MASK,

                    MESHHOLOGRAM_PROP_ENUM._BLEND_OP,
                    MESHHOLOGRAM_PROP_ENUM._SRC_BLEND,
                    MESHHOLOGRAM_PROP_ENUM._DST_BLEND,
                    MESHHOLOGRAM_PROP_ENUM._BLEND_OP_ALPHA,
                    MESHHOLOGRAM_PROP_ENUM._SRC_BLEND_ALPHA,
                    MESHHOLOGRAM_PROP_ENUM._DST_BLEND_ALPHA,
                }
            )},
            {PROPERTY_BLOCK.STENCIL,new PropertyBlock("Stencil",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_REF,
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_READ_MASK,
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_WRITE_MASK,
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_COMP,
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_PASS,
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_FAIL,
                    MESHHOLOGRAM_PROP_ENUM._STENCIL_Z_FAIL,
                }
            )},
            {PROPERTY_BLOCK.AUDIOLINK,new PropertyBlock("AudioLink",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._AUDIOLINK_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._AUDIOLINK_THEME_COLOR_BAND,
                }
            )},
            {PROPERTY_BLOCK.FRAGMENT,new PropertyBlock("Fragment",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_TRIANGLE_COMPRESSION,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_FILL,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_LINE_WIDTH,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_LINE_GRADIENT_BIAS,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_MANUAL_LINE_SCALING,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_LINE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_LINE_ANIMATION_MODE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_PARTITION_MODE,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_FIXED_VALUE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_SPACE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_OFFSET0,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_SCALE0,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_OFFSET1,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_SCALE1,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_OFFSET_BEFORE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_SEED,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_TIME_SPEED,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_TIME_PHASE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_NOISE_VALUE_SCALE,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_VU_BAND,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_VU_SMOOTHING,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_VU_PANNING,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_VU_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_CHRONO_TENSITY_MODE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_CHRONO_TENSITY_BAND,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_SPECTRUM_MIRROR,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_SPECTRUM_STRENGTH,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_MASK_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_OFFSET_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_OFFSET_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_AUDIOLINK_MASK_CONTROL,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_PHASE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_LOOP_MODE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_EASE_MODE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_EASE_CURVE,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_MID_MUL,
                    MESHHOLOGRAM_PROP_ENUM._FRAGMENT_MID_ADD,
                }
            )},
            {PROPERTY_BLOCK.COLOR,new PropertyBlock("Color",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._COLOR0,
                    MESHHOLOGRAM_PROP_ENUM._COLOR1,
                    MESHHOLOGRAM_PROP_ENUM._EMISSION,
                    MESHHOLOGRAM_PROP_ENUM._COLOR_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._COLOR_GRADIENT_TEX,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_PARTITION_MODE,
                    MESHHOLOGRAM_PROP_ENUM._AUDIOLINK_THEME_COLOR_BAND,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._COLORING_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_FIXED_VALUE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_SPACE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_OFFSET0,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_SCALE0,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_OFFSET1,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_SCALE1,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_OFFSET_BEFORE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_SEED,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_TIME_SPEED,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_TIME_PHASE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_NOISE_VALUE_SCALE,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_VU_BAND,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_VU_SMOOTHING,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_VU_PANNING,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_VU_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_CHRONO_TENSITY_MODE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_CHRONO_TENSITY_BAND,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_SPECTRUM_MIRROR,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_SPECTRUM_STRENGTH,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._COLORING_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_MASK_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_OFFSET_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_OFFSET_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_AUDIOLINK_MASK_CONTROL,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._COLORING_PHASE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_LOOP_MODE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_EASE_MODE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_EASE_CURVE,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_MID_MUL,
                    MESHHOLOGRAM_PROP_ENUM._COLORING_MID_ADD,
                }
            )},
            {PROPERTY_BLOCK.GEOMETRY,new PropertyBlock("Geometry",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_SCALE_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_SCALE_BOUNDS,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_PUSHPULL_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_PUSHPULL_BOUNDS,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_PUSHPULL_PARTITION_BIAS,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_ROTATION_ENABLE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_ROTATION_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_ROTATION_INVERT,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_ROTATION_NOISE_REPEAT,

                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_PIXELIZATION_SPACE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_PIXELIZATION,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_FIXED_VALUE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_SPACE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_OFFSET0,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_SCALE0,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_OFFSET1,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_SCALE1,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_OFFSET_BEFORE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_SEED,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_TIME_SPEED,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_TIME_PHASE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_NOISE_VALUE_SCALE,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_VU_BAND,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_VU_SMOOTHING,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_VU_PANNING,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_VU_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_CHRONO_TENSITY_MODE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_CHRONO_TENSITY_BAND,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_SPECTRUM_MIRROR,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_SPECTRUM_STRENGTH,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_MASK_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_OFFSET_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_OFFSET_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_AUDIOLINK_MASK_CONTROL,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_PHASE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_LOOP_MODE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_EASE_MODE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_EASE_CURVE,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_MID_MUL,
                    MESHHOLOGRAM_PROP_ENUM._GEOMETRY_MID_ADD,
                }
            )},
            {PROPERTY_BLOCK.ORBIT,new PropertyBlock("Orbit",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ENABLE,

                    MESHHOLOGRAM_PROP_ENUM._ORBIT_OFFSET,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_SCALE,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_FIXED_VALUE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_SEED,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_PRIMITIVE_RATIO,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_SPACE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_OFFSET0,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_SCALE0,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_OFFSET1,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_SCALE1,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_OFFSET_BEFORE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_SEED,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_TIME_SPEED,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_TIME_PHASE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_NOISE_VALUE_SCALE,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_VU_BAND,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_VU_SMOOTHING,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_VU_PANNING,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_VU_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_CHRONO_TENSITY_MODE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_CHRONO_TENSITY_BAND,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_SPECTRUM_MIRROR,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_SPECTRUM_STRENGTH,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_MASK_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_OFFSET_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_OFFSET_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_AUDIOLINK_MASK_CONTROL,
                },
                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_PHASE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_LOOP_MODE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_EASE_MODE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_EASE_CURVE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_MID_MUL,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_MID_ADD,
                }
            )},
            {PROPERTY_BLOCK.ORBIT_ROTATION,new PropertyBlock("OrbitRotation",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_SPREAD,
                },
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_FIXED_VALUE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_SEED,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_SPACE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_OFFSET0,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_SCALE0,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_OFFSET1,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_SCALE1,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_OFFSET_BEFORE_SCALE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_SEED,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_TIME_SPEED,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_TIME_PHASE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_NOISE_VALUE_SCALE,
                },
                null,
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_MASK_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_CONTROL,
                }
            )},
            {PROPERTY_BLOCK.ORBIT_WAVE,new PropertyBlock("OrbitWave",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_FREQUENCY,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_PHASE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_SPEED,
                },
                null,

                new MESHHOLOGRAM_PROP_ENUM[]
                {
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_VU_BAND,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_VU_SMOOTHING,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_VU_PANNING,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_VU_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_CHRONO_TENSITY_MODE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_CHRONO_TENSITY_BAND,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_SPECTRUM_MODE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_SPECTRUM_MIRROR,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_SPECTRUM_BOUNDS,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_WAVE_AUDIOLINK_SPECTRUM_STRENGTH,
                }
            )},
            {PROPERTY_BLOCK.ORBIT_ROTATION_OFFSET,new PropertyBlock("OrbitRotationOffset",
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_ANGLE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_SPEED,
                },
                null,
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_SOURCE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_BAND,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_SMOOTHING,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_PANNING,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_VU_STRENGTH,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_CHRONO_TENSITY_MODE,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_CHRONO_TENSITY_BAND,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_CHRONO_TENSITY_STRENGTH,
                },
                new MESHHOLOGRAM_PROP_ENUM[]{
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_MASK_CONTROL,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_MASK_CONTROL_TEX,
                    MESHHOLOGRAM_PROP_ENUM._ORBIT_ROTATION_OFFSET_AUDIOLINK_MASK_CONTROL,
                }
            )},
        };
    }
}

#endif